services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"  # Application port
      - "5678:5678"  # Debug port
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYDEVD_DISABLE_FILE_VALIDATION=1
      - SECRET_KEY=dev-secret-key
      - DATABASE_URL=sqlite:////app/instance/data.db
    entrypoint: []
    command: ["python", "-Xfrozen_modules=off", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "flask", "run", "--host", "0.0.0.0", "--port", "5001", "--no-debugger", "--no-reload"]
