version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: nada/docker/Dockerfile
    ports:
      - "8090:8080"
    environment:
      - FLASK_APP=nada/app
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-default-dev-key-change-in-production}
      - DATABASE_URL=sqlite:////app/nada/instance/data.db
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - PORT=8080
    volumes:
      - ./nada/instance:/app/nada/instance:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
