services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY:-default-dev-key-change-in-production}
      - DATABASE_URL=sqlite:////app/instance/data.db
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - PORT=5001
    volumes:
      - .:/app:rw
      - ./instance:/app/instance:rw
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: >
      sh -c "flask db upgrade &&
             python -m flask run --host=0.0.0.0 --port=5001"
