services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.app
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/instance/data.db
      - PORT=5001
    volumes:
      - ./instance:/app/instance:rw
      - ./config.json:/app/config.json:rw
      - type: bind
        source: ./migrations
        target: /app/migrations
        bind:
          create_host_path: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s  # Increased to allow for migrations
