"""initial

Revision ID: 0d995010f76d
Revises: 
Create Date: 2025-01-19 00:19:07.274719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d995010f76d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(TRUE)'))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('email')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(TRUE)'))
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('booking_date')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
